{% set conda_name = "datapackage-py" %}
{% set name = "datapackage" %}
{% set version = "1.2.3" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "461359132a72cbe6ae40d6630aecd539aa1966bd6707b2b10ea43b0363ce9f79" %}

package:
  name: {{ conda_name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six >=1.10,<2.0
    - click >=6.7,<7.0
    - requests >=2.8,<3.0
    - cchardet >=1.0,<2.0
    - jsonschema >=2.5,<3.0
    - unicodecsv >=0.14,<1.0
    - jsonpointer >=1.10,<2.0
    - tableschema >=1.0.7,<2.0
    - tabulator >=1.3,<2.0

test:
  imports:
    - datapackage

about:
  home: https://github.com/frictionlessdata/datapackage-py
  license_file: LICENSE.md
  license: MIT
  license_family: MIT
  summary: 'Utilities to work with Data Packages as defined on dataprotocols.org'
  dev_url: https://github.com/frictionlessdata/datapackage-py
  doc_url: https://github.com/frictionlessdata/datapackage-py

extra:
  recipe-maintainers:
    - pmlandwehr
