{% set conda_name = "datapackage-py" %}
{% set name = "datapackage" %}
{% set version = "1.9.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "8690de7f65e1a1f5ef503bc706f492cc8ec8a866742834f8f267c85441d0847b" %}
{% set build = 0 %}

package:
  name: {{ conda_name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - six >=1.10,<2.0a
    - requests >=2.8,<3.0a
    - jsonschema >=2.5,<3.0a
    - unicodecsv >=0.14,<1.0a
    - jsontableschema >=0.8,<1.0a
    - tabulator-py >=1.0.0a5,<2.0a

test:
  imports:
    - datapackage

about:
  home: https://github.com/frictionlessdata/datapackage-py
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'Utilities to work with Data Packages as defined on dataprotocols.org'
  dev_url: https://github.com/frictionlessdata/datapackage-py
  doc_url: https://github.com/frictionlessdata/datapackage-py

extra:
  recipe-maintainers:
    - pmlandwehr
